### ISSUE TITLE
Questions for homework 6: practical python (biopython)

### ISSUE THREAD

**Issue by k8hertweck** [fredhutchio/tfcb_2019#34]
Homework questions here

@jbloom and I are happy to answer questions about the homework here. For general questions about command line, please use #35

**Comment by alexgal8** [comment]
For question 1: I have this code:
def reverse_complement(seq):
    rc_dict = {'A': 'T', 'T': 'A', 'G': 'C', 'C': 'G'}
    revcomplement = []
    for nt in reversed(seq.upper()):
        revcomplement.append(rc_dict[nt])
    return ''.join(revcomplement)

! head -n 8 barcodes_R1.fastq

import Bio.SeqIO

seqreads = list(Bio.SeqIO.parse('barcodes_R1.fastq', format='fastq'))

seqreads_str_2 = []
for s in seqreads:
    seqreads_str_2.append(str(s.seq))

reverse_complement(seqreads_str_2)

I am getting the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-28-053008da97c3> in <module>
     34     seqreads_str_2.append(str(s.seq))
     35 
---> 36 reverse_complement(seqreads_str_2)
     37 

<ipython-input-28-053008da97c3> in reverse_complement(seq)
     20     rc_dict = {'A': 'T', 'T': 'A', 'G': 'C', 'C': 'G'}
     21     revcomplement = []
---> 22     for nt in reversed(seq.upper()):
     23         revcomplement.append(rc_dict[nt])
     24     return ''.join(revcomplement)

AttributeError: 'list' object has no attribute 'upper'

I believe this error is because it is saying seqreads_str_2 is a list and you can't use upper on list. But I thought 
seqreads_str_2 = []
for s in seqreads:
    seqreads_str_2.append(str(s.seq)) 
made seqreads_str_2 a string?

**Comment by jbloom** [comment]
I have a hard time following the question as you don't have formatting or indentation in the code (next time put it in Markdown formatting or attach a screenshot), but as best I understand this is the problem and how to fix it:

It appears to me that you are trying to apply the function `reverse_complement` to the list of strings `seqreads_str_2`. But `reverse_complement` takes strings, so you need to apply it to each string in `seqreads_str_2` separately. Try something like this:
```
seqreads_str_2 = []
for s in seqreads:
    seqreads_str_2.append(reverse_complement(str(s.seq)))
```

In the above code, you are applying `reverse_complement` to each str, not the whole list of them.
